version: "3"
services:
  frontend:
    image: client-app
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app

  backend:
    image: server-app
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge


